// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspnetserver.Data;

#nullable disable

namespace aspnetserver.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("aspnetserver.Data.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("TaskId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            Content = "This is Task 1 and it has some very interesting content.",
                            Title = "Task 1"
                        },
                        new
                        {
                            TaskId = 2,
                            Content = "This is Task 2 and it has some very interesting content.",
                            Title = "Task 2"
                        },
                        new
                        {
                            TaskId = 3,
                            Content = "This is Task 3 and it has some very interesting content.",
                            Title = "Task 3"
                        },
                        new
                        {
                            TaskId = 4,
                            Content = "This is Task 4 and it has some very interesting content.",
                            Title = "Task 4"
                        },
                        new
                        {
                            TaskId = 5,
                            Content = "This is Task 5 and it has some very interesting content.",
                            Title = "Task 5"
                        },
                        new
                        {
                            TaskId = 6,
                            Content = "This is Task 6 and it has some very interesting content.",
                            Title = "Task 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
